-- Add profile fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS weight_kg DECIMAL(10, 2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS height_cm DECIMAL(10, 2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS target_weight_kg DECIMAL(10, 2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS fitness_goal VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS activity_level VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS weekly_workout_target INTEGER;
